spring.application.name=outbox-dispatcher

spring.jpa.hibernate.ddl-auto=none
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/workflow
spring.datasource.username=workflow
spring.datasource.password=workflow
spring.datasource.driver-class-name=org.postgresql.Driver